/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Mood = IDL.Variant({
  'sad' : IDL.Null,
  'melancholic' : IDL.Null,
  'happy' : IDL.Null,
  'angry' : IDL.Null,
  'romantic' : IDL.Null,
  'calm' : IDL.Null,
  'chill' : IDL.Null,
  'energetic' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'currentMood' : Mood,
  'joined' : IDL.Int,
  'avatarUrl' : IDL.Text,
});
export const VibeCircleView = IDL.Record({
  'members' : IDL.Vec(IDL.Principal),
  'themeMood' : Mood,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
});
export const VibePost = IDL.Record({
  'songTitle' : IDL.Text,
  'mood' : Mood,
  'author' : IDL.Principal,
  'youtubeId' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'artistName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCircle' : IDL.Func([IDL.Text, Mood], [], []),
  'createProfile' : IDL.Func([IDL.Text, IDL.Text, Mood, IDL.Text], [], []),
  'createVibePost' : IDL.Func(
      [Mood, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCircleMembers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getCirclesByMood' : IDL.Func(
      [Mood],
      [IDL.Vec(IDL.Tuple(IDL.Text, VibeCircleView))],
      ['query'],
    ),
  'getFriendFeed' : IDL.Func([], [IDL.Vec(VibePost)], ['query']),
  'getFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getGlobalFeed' : IDL.Func([], [IDL.Vec(VibePost)], ['query']),
  'getPendingFriendRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getPostsByMood' : IDL.Func([Mood], [IDL.Vec(VibePost)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinCircle' : IDL.Func([IDL.Text], [], []),
  'leaveCircle' : IDL.Func([IDL.Text], [], []),
  'rejectFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'unfriend' : IDL.Func([IDL.Principal], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text, Mood, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Mood = IDL.Variant({
    'sad' : IDL.Null,
    'melancholic' : IDL.Null,
    'happy' : IDL.Null,
    'angry' : IDL.Null,
    'romantic' : IDL.Null,
    'calm' : IDL.Null,
    'chill' : IDL.Null,
    'energetic' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'currentMood' : Mood,
    'joined' : IDL.Int,
    'avatarUrl' : IDL.Text,
  });
  const VibeCircleView = IDL.Record({
    'members' : IDL.Vec(IDL.Principal),
    'themeMood' : Mood,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
  });
  const VibePost = IDL.Record({
    'songTitle' : IDL.Text,
    'mood' : Mood,
    'author' : IDL.Principal,
    'youtubeId' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'artistName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCircle' : IDL.Func([IDL.Text, Mood], [], []),
    'createProfile' : IDL.Func([IDL.Text, IDL.Text, Mood, IDL.Text], [], []),
    'createVibePost' : IDL.Func(
        [Mood, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCircleMembers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getCirclesByMood' : IDL.Func(
        [Mood],
        [IDL.Vec(IDL.Tuple(IDL.Text, VibeCircleView))],
        ['query'],
      ),
    'getFriendFeed' : IDL.Func([], [IDL.Vec(VibePost)], ['query']),
    'getFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getGlobalFeed' : IDL.Func([], [IDL.Vec(VibePost)], ['query']),
    'getPendingFriendRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getPostsByMood' : IDL.Func([Mood], [IDL.Vec(VibePost)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinCircle' : IDL.Func([IDL.Text], [], []),
    'leaveCircle' : IDL.Func([IDL.Text], [], []),
    'rejectFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'unfriend' : IDL.Func([IDL.Principal], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text, Mood, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };