/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : string,
  'to' : Principal,
  'from' : Principal,
  'text' : string,
  'timestamp' : bigint,
}
export type Mood = { 'sad' : null } |
  { 'melancholic' : null } |
  { 'happy' : null } |
  { 'angry' : null } |
  { 'romantic' : null } |
  { 'calm' : null } |
  { 'chill' : null } |
  { 'energetic' : null };
export interface PlaylistTrack {
  'songTitle' : string,
  'youtubeId' : string,
  'artistName' : string,
}
export interface PlaylistView {
  'id' : string,
  'owner' : Principal,
  'tracks' : Array<PlaylistTrack>,
  'name' : string,
  'createdAt' : bigint,
}
export interface UserProfile {
  'bio' : string,
  'principal' : Principal,
  'username' : string,
  'displayName' : string,
  'currentMood' : Mood,
  'joined' : bigint,
  'avatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VibeCircleView {
  'members' : Array<Principal>,
  'themeMood' : Mood,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
}
export interface VibePost {
  'songTitle' : string,
  'mood' : Mood,
  'author' : Principal,
  'youtubeId' : string,
  'message' : [] | [string],
  'timestamp' : bigint,
  'artistName' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<[Principal], undefined>,
  'addToFriendPlaylist' : ActorMethod<[string, PlaylistTrack], undefined>,
  'addToPlaylist' : ActorMethod<[string, PlaylistTrack], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCircle' : ActorMethod<[string, Mood], undefined>,
  'createPlaylist' : ActorMethod<[string], string>,
  'createProfile' : ActorMethod<
    [string, string, string, Mood, string],
    undefined
  >,
  'createVibePost' : ActorMethod<
    [Mood, string, string, string, [] | [string]],
    undefined
  >,
  'deleteConversation' : ActorMethod<[Principal], undefined>,
  'deleteMessage' : ActorMethod<[string, Principal], undefined>,
  'deletePlaylist' : ActorMethod<[string], undefined>,
  'deleteVibePost' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCircleMembers' : ActorMethod<[string], Array<Principal>>,
  'getCirclesByMood' : ActorMethod<[Mood], Array<[string, VibeCircleView]>>,
  'getConversation' : ActorMethod<[Principal], Array<ChatMessage>>,
  'getFriendFeed' : ActorMethod<[], Array<VibePost>>,
  'getFriendPlaylists' : ActorMethod<[Principal], Array<PlaylistView>>,
  'getFriends' : ActorMethod<[], Array<Principal>>,
  'getGlobalFeed' : ActorMethod<[], Array<VibePost>>,
  'getMyPlaylists' : ActorMethod<[], Array<PlaylistView>>,
  'getPendingFriendRequests' : ActorMethod<[], Array<Principal>>,
  'getPostsByMood' : ActorMethod<[Mood], Array<VibePost>>,
  'getProfile' : ActorMethod<[Principal], UserProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUsernameTaken' : ActorMethod<[string], boolean>,
  'joinCircle' : ActorMethod<[string], undefined>,
  'leaveCircle' : ActorMethod<[string], undefined>,
  'rejectFriendRequest' : ActorMethod<[Principal], undefined>,
  'removeFromFriendPlaylist' : ActorMethod<[string, bigint], undefined>,
  'removeFromPlaylist' : ActorMethod<[string, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendFriendRequest' : ActorMethod<[Principal], undefined>,
  'sendFriendRequestByUsername' : ActorMethod<[string], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'unfriend' : ActorMethod<[Principal], undefined>,
  'updateProfile' : ActorMethod<
    [string, string, string, Mood, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];