/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VibePost {
    songTitle: string;
    mood: Mood;
    author: Principal;
    youtubeId: string;
    message?: string;
    timestamp: bigint;
    artistName: string;
}
export interface PlaylistView {
    id: string;
    owner: Principal;
    tracks: Array<PlaylistTrack>;
    name: string;
    createdAt: bigint;
}
export interface PlaylistTrack {
    songTitle: string;
    youtubeId: string;
    artistName: string;
}
export interface ChatMessage {
    id: string;
    to: Principal;
    from: Principal;
    text: string;
    timestamp: bigint;
}
export interface UserProfile {
    bio: string;
    principal: Principal;
    username: string;
    displayName: string;
    currentMood: Mood;
    joined: bigint;
    avatarUrl: string;
}
export interface VibeCircleView {
    members: Array<Principal>;
    themeMood: Mood;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
}
export enum Mood {
    sad = "sad",
    melancholic = "melancholic",
    happy = "happy",
    angry = "angry",
    romantic = "romantic",
    calm = "calm",
    chill = "chill",
    energetic = "energetic"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptFriendRequest(from: Principal): Promise<void>;
    addToFriendPlaylist(playlistId: string, track: PlaylistTrack): Promise<void>;
    addToPlaylist(playlistId: string, track: PlaylistTrack): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCircle(name: string, themeMood: Mood): Promise<void>;
    createPlaylist(name: string): Promise<string>;
    createProfile(displayName: string, username: string, avatarUrl: string, currentMood: Mood, bio: string): Promise<void>;
    createVibePost(mood: Mood, youtubeId: string, songTitle: string, artistName: string, message: string | null): Promise<void>;
    deleteConversation(friend: Principal): Promise<void>;
    deleteMessage(messageId: string, friend: Principal): Promise<void>;
    deletePlaylist(playlistId: string): Promise<void>;
    deleteVibePost(timestamp: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCircleMembers(name: string): Promise<Array<Principal>>;
    getCirclesByMood(mood: Mood): Promise<Array<[string, VibeCircleView]>>;
    getConversation(friend: Principal): Promise<Array<ChatMessage>>;
    getFriendFeed(): Promise<Array<VibePost>>;
    getFriendPlaylists(friend: Principal): Promise<Array<PlaylistView>>;
    getFriends(): Promise<Array<Principal>>;
    getGlobalFeed(): Promise<Array<VibePost>>;
    getMyPlaylists(): Promise<Array<PlaylistView>>;
    getPendingFriendRequests(): Promise<Array<Principal>>;
    getPostsByMood(mood: Mood): Promise<Array<VibePost>>;
    getProfile(user: Principal): Promise<UserProfile>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isUsernameTaken(username: string): Promise<boolean>;
    joinCircle(name: string): Promise<void>;
    leaveCircle(name: string): Promise<void>;
    rejectFriendRequest(from: Principal): Promise<void>;
    removeFromFriendPlaylist(playlistId: string, index: bigint): Promise<void>;
    removeFromPlaylist(playlistId: string, index: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendFriendRequest(to: Principal): Promise<void>;
    sendFriendRequestByUsername(username: string): Promise<void>;
    sendMessage(to: Principal, text: string): Promise<void>;
    unfriend(user: Principal): Promise<void>;
    updateProfile(displayName: string, username: string, avatarUrl: string, currentMood: Mood, bio: string): Promise<void>;
}
import type { Mood as _Mood, UserProfile as _UserProfile, UserRole as _UserRole, VibeCircleView as _VibeCircleView, VibePost as _VibePost } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptFriendRequest(arg0);
            return result;
        }
    }
    async addToFriendPlaylist(arg0: string, arg1: PlaylistTrack): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToFriendPlaylist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToFriendPlaylist(arg0, arg1);
            return result;
        }
    }
    async addToPlaylist(arg0: string, arg1: PlaylistTrack): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToPlaylist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToPlaylist(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCircle(arg0: string, arg1: Mood): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCircle(arg0, to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCircle(arg0, to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPlaylist(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlaylist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlaylist(arg0);
            return result;
        }
    }
    async createProfile(arg0: string, arg1: string, arg2: string, arg3: Mood, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, arg1, arg2, to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, arg1, arg2, to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async createVibePost(arg0: Mood, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createVibePost(to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVibePost(to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async deleteConversation(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteConversation(arg0);
            return result;
        }
    }
    async deleteMessage(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0, arg1);
            return result;
        }
    }
    async deletePlaylist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlaylist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlaylist(arg0);
            return result;
        }
    }
    async deleteVibePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVibePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVibePost(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCircleMembers(arg0: string): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCircleMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCircleMembers(arg0);
            return result;
        }
    }
    async getCirclesByMood(arg0: Mood): Promise<Array<[string, VibeCircleView]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCirclesByMood(to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCirclesByMood(to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: Principal): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return result;
        }
    }
    async getFriendFeed(): Promise<Array<VibePost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendFeed();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendFeed();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFriendPlaylists(arg0: Principal): Promise<Array<PlaylistView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendPlaylists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendPlaylists(arg0);
            return result;
        }
    }
    async getFriends(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriends();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriends();
            return result;
        }
    }
    async getGlobalFeed(): Promise<Array<VibePost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalFeed();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalFeed();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPlaylists(): Promise<Array<PlaylistView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPlaylists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPlaylists();
            return result;
        }
    }
    async getPendingFriendRequests(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingFriendRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingFriendRequests();
            return result;
        }
    }
    async getPostsByMood(arg0: Mood): Promise<Array<VibePost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByMood(to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByMood(to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_UserProfile_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_UserProfile_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isUsernameTaken(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUsernameTaken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUsernameTaken(arg0);
            return result;
        }
    }
    async joinCircle(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinCircle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinCircle(arg0);
            return result;
        }
    }
    async leaveCircle(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveCircle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveCircle(arg0);
            return result;
        }
    }
    async rejectFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectFriendRequest(arg0);
            return result;
        }
    }
    async removeFromFriendPlaylist(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromFriendPlaylist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromFriendPlaylist(arg0, arg1);
            return result;
        }
    }
    async removeFromPlaylist(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromPlaylist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromPlaylist(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFriendRequest(arg0);
            return result;
        }
    }
    async sendFriendRequestByUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFriendRequestByUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFriendRequestByUsername(arg0);
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async unfriend(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfriend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfriend(arg0);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string, arg3: Mood, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2, to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2, to_candid_Mood_n3(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
}
function from_candid_Mood_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mood): Mood {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_VibeCircleView_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VibeCircleView): VibeCircleView {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_VibePost_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VibePost): VibePost {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    members: Array<Principal>;
    themeMood: _Mood;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
}): {
    members: Array<Principal>;
    themeMood: Mood;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
} {
    return {
        members: value.members,
        themeMood: from_candid_Mood_n9(_uploadFile, _downloadFile, value.themeMood),
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    songTitle: string;
    mood: _Mood;
    author: Principal;
    youtubeId: string;
    message: [] | [string];
    timestamp: bigint;
    artistName: string;
}): {
    songTitle: string;
    mood: Mood;
    author: Principal;
    youtubeId: string;
    message?: string;
    timestamp: bigint;
    artistName: string;
} {
    return {
        songTitle: value.songTitle,
        mood: from_candid_Mood_n9(_uploadFile, _downloadFile, value.mood),
        author: value.author,
        youtubeId: value.youtubeId,
        message: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.message)),
        timestamp: value.timestamp,
        artistName: value.artistName
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    principal: Principal;
    username: string;
    displayName: string;
    currentMood: _Mood;
    joined: bigint;
    avatarUrl: string;
}): {
    bio: string;
    principal: Principal;
    username: string;
    displayName: string;
    currentMood: Mood;
    joined: bigint;
    avatarUrl: string;
} {
    return {
        bio: value.bio,
        principal: value.principal,
        username: value.username,
        displayName: value.displayName,
        currentMood: from_candid_Mood_n9(_uploadFile, _downloadFile, value.currentMood),
        joined: value.joined,
        avatarUrl: value.avatarUrl
    };
}
function from_candid_tuple_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _VibeCircleView]): [string, VibeCircleView] {
    return [
        value[0],
        from_candid_VibeCircleView_n15(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sad: null;
} | {
    melancholic: null;
} | {
    happy: null;
} | {
    angry: null;
} | {
    romantic: null;
} | {
    calm: null;
} | {
    chill: null;
} | {
    energetic: null;
}): Mood {
    return "sad" in value ? Mood.sad : "melancholic" in value ? Mood.melancholic : "happy" in value ? Mood.happy : "angry" in value ? Mood.angry : "romantic" in value ? Mood.romantic : "calm" in value ? Mood.calm : "chill" in value ? Mood.chill : "energetic" in value ? Mood.energetic : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _VibeCircleView]>): Array<[string, VibeCircleView]> {
    return value.map((x)=>from_candid_tuple_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VibePost>): Array<VibePost> {
    return value.map((x)=>from_candid_VibePost_n18(_uploadFile, _downloadFile, x));
}
function to_candid_Mood_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): _Mood {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    principal: Principal;
    username: string;
    displayName: string;
    currentMood: Mood;
    joined: bigint;
    avatarUrl: string;
}): {
    bio: string;
    principal: Principal;
    username: string;
    displayName: string;
    currentMood: _Mood;
    joined: bigint;
    avatarUrl: string;
} {
    return {
        bio: value.bio,
        principal: value.principal,
        username: value.username,
        displayName: value.displayName,
        currentMood: to_candid_Mood_n3(_uploadFile, _downloadFile, value.currentMood),
        joined: value.joined,
        avatarUrl: value.avatarUrl
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): {
    sad: null;
} | {
    melancholic: null;
} | {
    happy: null;
} | {
    angry: null;
} | {
    romantic: null;
} | {
    calm: null;
} | {
    chill: null;
} | {
    energetic: null;
} {
    return value == Mood.sad ? {
        sad: null
    } : value == Mood.melancholic ? {
        melancholic: null
    } : value == Mood.happy ? {
        happy: null
    } : value == Mood.angry ? {
        angry: null
    } : value == Mood.romantic ? {
        romantic: null
    } : value == Mood.calm ? {
        calm: null
    } : value == Mood.chill ? {
        chill: null
    } : value == Mood.energetic ? {
        energetic: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
